name: Deployment
run-name: Deployment in ${{ inputs.target-environment }}/${{ inputs.target-region }} of ${{ inputs.target-image-tag }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      target-environment:
        type: choice
        description: 'Target environment for deployment'
        required: true
        options:
          - test
          - int
          - e2e
          - prod
        target-region:
        type: choice
        description: "AWS region for deployment"
        required: true
        options:
          - cn-north-1
          - cn-north-2
          - cn-north-3
      target-image-tag:
        type: string
        description: 'Set base image to deploy. ex: test-xxx'
        required: true
concurrency:
  group: ${{ github.workflow }}-${{ inputs.target-environment }}-${{ inputs.target-region }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  deploy:
    name: Deploy to "${{ inputs.target-environment }}" environment in "${{ inputs.target-region }}" region - "${{ inputs.target-image-tag }}"
    runs-on: "cawe-linux-x64-compute-medium"
    steps:
      - name: Check target-environment & target-region
      shell: bash
      run:
        environment="${{ inputs.target-environment }}"
        region="${{ inputs.target-region }}"

        if [[ "$environment" == "test" && ! "$region" =~ ^(cn-north-1)$ ]]; then
          echo "Invalid - Deployments for $environment deployment can only be performed to cn-north-1, not $region"
          exit 1
        elif [[ "$environment" == "int" && ! "$region" =~ ^(cn-north-1)$ ]]; then
          echo "Invalid - Deployments for $environment environment can only be performed to cn-north-1, not $region"
          exit 1
        else
         echo "Valid - Deployments for $environment environment can be performed to $region"
         if
